import {
  PlusIcon,
  ThreeDotsIcon,
  MainDachIcon,
  CompentenciesIcon,
  GoalsIcon,
  Feedback,
  Reviews,
  Surveys,
  Learning,
  Compensation,
  Settings,
  DraweArrow,
  DateFeedbackIcon,
  LogoInnova,
  ArrowDownBlack,
  ArrowDownWhite,
  Notification,
  SearchIcon,
  PopUpDeleteIcon,
  MessageFavFeedbackIcon,
  RightFeedbackIcon,
  MessageFeedbackIcon,
  RedFeedback,
  GreenFeedback,
  ArrowRight,
  DrawerLeft,
  SortIcon,
  DraweArrowRight,
} from "../assets/icons/icons";

const Icons = {
  PlusIcon,
  ThreeDotsIcon,
  MainDachIcon,
  CompentenciesIcon,
  GoalsIcon,
  Feedback,
  Reviews,
  Surveys,
  Learning,
  Compensation,
  Settings,
  DraweArrow,
  DateFeedbackIcon,
  LogoInnova,
  ArrowDownBlack,
  ArrowDownWhite,
  Notification,
  SearchIcon,
  PopUpDeleteIcon,
  MessageFavFeedbackIcon,
  RightFeedbackIcon,
  MessageFeedbackIcon,
  RedFeedback,
  GreenFeedback,
  ArrowRight,

  DrawerLeft,
  DraweArrowRight,

  SortIcon,
};
export default Icons;
