import {
    PlusIcon,
    ThreeDotsIcon,
    MainDachIcon,
    CompentenciesIcon,
    GoalsIcon,
    Feedback,
    Reviews,
    Surveys,
    Learning,
    Compensation,
    Settings,
    DraweArrow,
    DateFeedbackIcon,
    LogoInnova,
    ArrowDownBlack,
    ArrowDownWhite,
    Notification,
    SearchIcon
} from "../assets/icons/icons"
const Icons = {
    PlusIcon,
    ThreeDotsIcon,
    MainDachIcon,
    CompentenciesIcon,
    GoalsIcon,
    Feedback,
    Reviews,
    Surveys,
    Learning,
    Compensation,
    Settings,
    DraweArrow,
    DateFeedbackIcon,
    LogoInnova,
    ArrowDownBlack,
    ArrowDownWhite,
    Notification,
    SearchIcon
}
export default Icons;